### ISSUE TITLE
CSRF not present in SailsSocketService

### ISSUE THREAD

**Issue by tibotiber** [huafu/ember-data-sails#15]
Hi @huafu, 
I'm trying to use the socket service but I'm getting an issue due to csrf settings. My call is as follow:
```
this.sailsSocket.request('post', '/support/post', postData).then(function(response) {
    console.log(response);
}
```
and I get the following error (doesn't even reach `console.log`):
```
[ed-sails] triggering event `didConnect`

undefined ember.debug.js:28602
RSVP.onerrorDefault  ember.debug.js:28602
__exports__.default.trigger ember.debug.js:51120
Promise._onerror ember.debug.js:52132
publishRejection ember.debug.js:50363
(anonymous function) ember.debug.js:28563
Queue.invoke ember.debug.js:854
Queue.flush ember.debug.js:919
DeferredActionQueues.flush ember.debug.js:724
Backburner.end ember.debug.js:149
(anonymous function) ember.debug.js:552 
```
Now, if I manually fetch the csrf token with postman and add it to `postData` before making the request, everything works just fine.

My settings are as follow:
```
export default SailsSocketAdapter.extend({
    useCSRF: true,
    coalesceFindRequests: true
});
```
Is the socket service inheriting the config of the socket adapter? If not, is there any extra settings for the socket service?
Thanks :)

**Comment by huafu** [comment]
The device is independent of the adapter. You need to add the CSRF yourself in the data to send if you are not using the adapter and intent to do CSRF verification in that endpoint.
 This is not a bug it's actually normal ;-)

**Comment by tibotiber** [comment]
Thanks for the details. Any chance that automatic fetch of CSRF token will be supported on standalone (no adapter) socket service usage in the future? If not, what is the rationale for this choice? I'm curious ;)
