### ISSUE TITLE
Injection of sailsSocket in components

### ISSUE THREAD

**Issue by tibotiber** [huafu/ember-data-sails#17]
Hi! Would you mind injecting `sailsSocket` in components as well?

**Comment by kpullen** [comment]
`SailsSocket` is a service, so you can just inject it into any component you wish. Just do something like:

```
//app/ui/components/realtime-component/component.js
import Ember from 'ember';

export default Ember.Component.extend({
  sailsSocket: Ember.inject.service()
});
```

Alternatively you may be able to inject it using an instance initializer, though I'll admit I've never done that before.

**Comment by huafu** [comment]
Thx for answering @kpullen
