### ISSUE TITLE
how to get socket to connect on anything other than port 4200?

### ISSUE THREAD

**Issue by shopapps** [huafu/ember-data-sails#22]
Please help as I must be missing a config somewhere...

I have a sails server running on port 1337
I have my app running as ember serve on port 4200
when I load the app in a browser I get streams of connection requests in firebug of:

GET http://localhost:4200/socket.io/?__sails_io_sdk_version=0.11.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&EIO=3&transport=polling&t=1438000496354-2

if i do a view source of the browser i see:

    <script type="text/javascript" id="eds-sails-io-script" src="//localhost:1337/js/dependencies/sails.io.js"></script>
    <script type="text/javascript">io.sails.autoConnect = false; io.sails.emberDataSailsReady = true;</script>

my config/environment.js contains:

    APP: {
      SAILS_LOG_LEVEL: 'debug',
      emberDataSails:  {
        host: '//localhost:1337',
        socketUrl: '//localhost:1337',
      }
    }

versions are:
ember-cli : 1.13.5
sails: 0.11.0
ember-data-sail : 0.0.15

what do i need to do, to get the socket to connect to port 1337 instead of 4200?  thanks.

**Comment by shopapps** [comment]
I gave this another go (rebuild of sails server).  The issue goes away if i remove:

    app.import('vendor/sails.io.js');

from my **ember-cli-build.js** file, and the socket connection does seem to work ok..

Is this something you would expect?

**Comment by huafu** [comment]
Hi @shopapps, sorry to answer *THAAAAAT* late, have been busy on many other projects :/
Yes you should not import the sails.io.js script, this addon is doing it.
