### ISSUE TITLE
Primary Key change

### ISSUE THREAD

**Issue by shopapps** [huafu/ember-data-sails#23]
Hello,

I am trying to use the socketAdapter to get data in/out of a sails API server.  I can get lists of my model (called 'requestType' ) ok, however when the system tries to grab a single record it seems to send params of

{ requestType_id: 6 }

but if this is passed to the store.query call then nothing gets returned. If however I change the params object to:

{ id: 6 }

then I get a single record returned ok.

My question is where is the best place to change this to get the two systems communicating, is it a serialiser, in the model call of each route or on the API?

**Comment by huafu** [comment]
I think here is more a ember-data related question, I believe you have to extend the adapter and/or serializer to do this

**Comment by shopapps** [comment]
OK, thanks.  I think it was just my naive understanding of how ember-data works, I was kinda assuming everything would just be automagic.   sadly it's not...  :-D
