### ISSUE TITLE
Could not find module `ember-data-sails/config/environment

### ISSUE THREAD

**Issue by jimmyjamieson** [huafu/ember-data-sails#26]
I've set everything up, created a simple user model/route in sails and ember. My sails API outputs the correct JSON and I've set up my SailsRESTAdapter.
```javascript
{
  "users": [
    {
      "createdAt": "2015-08-12T10:54:00.946Z",
      "updatedAt": "2015-08-12T10:54:00.946Z",
      "id": 1
    },
    {
      "createdAt": "2015-08-12T10:54:09.329Z",
      "updatedAt": "2015-08-12T10:54:09.329Z",
      "id": 2
    },
    {
      "createdAt": "2015-08-12T10:54:13.391Z",
      "updatedAt": "2015-08-12T10:54:13.391Z",
      "id": 3
    }
  ]
}
```
But when i go to localhost:4200/users, i get a console error:

**Error while processing route: users Could not find module `ember-data-sails/config/environment` imported from `ember-data-sails/serializers/sails` Error: Could not find module `ember-data-sails/config/environment` imported from `ember-data-sails/serializers/sails`**

Any idea what this could be?

**Comment by sangdukseo** [comment]
I am getting the exact same error.

**Comment by jimmyjamieson** [comment]
That's ember 2.0 officially released http://emberjs.com/blog/2015/08/13/ember-2-0-released.html - So it would be good to get this working so we can all move on with the shiny new things.

**Comment by mylen** [comment]
:+1:

**Comment by gunnar2k** [comment]
:+1:

**Comment by heartsentwined** [comment]
hacked around it at https://github.com/heartsentwined/ember-data-sails

**Comment by heartsentwined** [comment]
works for me - but I disabled the `use blueprints` switch, which is the _only_ dep on the config as far as I know. I don't need blueprints.

**Comment by wayne-o** [comment]
So I pulled your repo into my packages and I'm still getting this error - is there anything special I need to do?

**Comment by huafu** [comment]
I am fixing this now, will deploy `0.0.17` soon which will fix this.

**Comment by wayne-o** [comment]
👍

**Comment by jimmyjamieson** [comment]
:ok_hand:
