### ISSUE TITLE
404 error http://localhost:4200/socket.io/

### ISSUE THREAD

**Issue by mickyginger** [huafu/ember-data-sails#3]
I've set up using the README, with `ENV.APP.emberDataSails.socketUrl` set to 'localhost:1337' and `app.import('vendor/js/sails.io.js')` added to the Brocfile, but I keep getting this error:

`GET http://localhost:4200/socket.io/1/?__sails_io_sdk_version=0.10.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1425331004329 404 (Not Found)`

I'm assuming that request should be pointing to port 1337

__UPDATE__
I've managed to get it pointing to port 1337, by adding:

    <script>
        io.sails.url = 'http://localhost:1337';
    </script>

to my index.html file, but I'm still getting the same error:
`GET http://localhost:1337/socket.io/1/?__sails_io_sdk_version=0.10.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1425331004329 404 (Not Found)`

If I `curl 'http://localhost:1337/socket.io/1/?__sails_io_sdk_version=0.10.0&__sails_io_sdk_platform=browser&__sails_io_sdk_language=javascript&t=1425331004329' ` I get `{"code":0,"message":"Transport unknown"}`

**Comment by huafu** [comment]
closing in favor of #2. Hoping to have time to publish a new version before next week. But waiting for this, you can always use master branch:
```bash
npm install --save huafu/ember-data-sails#2fa783a4
```
