### ISSUE TITLE
No more generators

### ISSUE THREAD

**Issue by Systho** [huafu/ember-data-sails#4]
I don't think there is any more generators needed if you directly fetch the sails.io.js script from sails.

On the other hand you need to update your ember cli content security policy like this : 

```
    // allow to fetch the script
    ENV.contentSecurityPolicy['script-src'] += ' http://localhost:1337';
    // allow the websocket to connect
    ENV.contentSecurityPolicy['connect-src'] += ' http://localhost:1337 ws://localhost:1337';
```

**Comment by huafu** [comment]
Yup, no more generators. Did I forgot that in readme? Did I forgot to remove the blueprints folder?
