### ISSUE TITLE
Bind listeners on custom events

### ISSUE THREAD

**Issue by Systho** [huafu/ember-data-sails#5]
In sails I'm triggering or broadcasting custom websocket events using snipptes like this : 

```javascript
sails.sockets.broadcast(roomName, "myCustomEvent",
          {
            payloadProperty1: payloadValue1,
            payloadProperty2: payloadValue2,
          }
        );
```

Using your service I can try to listen on those events with the following snippet (this is coffeescript, I use it to differentiate my code from your code )

```coffeescript
@sailsSocket.listenFor 'myCustomEvent'
@sailsSocket.on 'myCustomEvent.undefined', @myCallback
```

the reason for the '.undefined' is because you suppose the existence of a verb property in the message which I didn't put.

```javascript
handleSocketMessage: function (event, message) {
      if (!isAlive(this)) {
        return;
      }
      this.trigger(event + '.' + message.verb, message);
    },
```

I could add a verb to my payload but I think it's not very natural since the sails doc doesn't talk about it  ( http://sailsjs.org/#!/documentation/reference/websockets/sails.sockets/sails.sockets.broadcast.html ).

I think the better idea is for you to add the verb on your ember even only if it exists and would even suggest to go further and trigger a "global" ember event all the time without the verb and a second "focused" event with the verb if there is one. This would allow to bind either for a specific verb or fall all the possible sub events of an event.

I also find it a little bit weird to be forced to `listenFor` an event before being able to call `on` on the service. it would be easier if calling `on` (or another method name if you do not want to break your api ) would bind the listener and register the callback at the same time

**Comment by huafu** [comment]
I guess I'll just remove it when verb is undefined ;-)

Thanks for the PR, will try to find some time ASAP to fix this issue.
