### ISSUE TITLE
SocketAdapter: findHasMany does not subscribe

### ISSUE THREAD

**Issue by toovy** [huafu/ember-data-sails#7]
Hi there,

I'm testing this adapter and I'm having an issue with a hasMany relationship. In my case a Page has many Content Areas. I've extended sails to add a links hash to the response, in this case like so:

    page: {
        ...
        links: [
           { contentareas: "/page/2/contentareas" }
       ]
    }

The adapter parses the response as expected and fetches the content areas. Due to debugging I found out that the _listenToSocket is called in buildURL, but buildURL is never called with the contentarea model in findHasMany. So the contentarea model is not subscribed, the async relationship does not automatically update. I came up with a quick fix by implementing findHasMany in sails-socket.js like so:

    var get = Ember.get;

    // [...]

    findHasMany: function(store, record, url, relationship) {
        var host = get(this, 'host');
        var id   = get(record, 'id');
        var type = record.constructor.typeKey;

       if (host && url.charAt(0) === '/' && url.charAt(1) !== '/') {
          url = host + url;
        }
        this._listenToSocket(relationship.type.typeKey); // <--- NEW NEW NEW
        return this.ajax(this.urlPrefix(url, this.buildURL(type, id)), 'GET');
    }

With this fix the async hasMany relationship automatically subscribes. As I've not yet written any adapters I'm not sure if this is a good way to solve the problem. Any thoughts? How was it thought to handle the async hasMany case in ember-data-sails (should the links hash be used?)?

Thanks, BR, toovy

**Comment by huafu** [comment]
Thanks for reporting!

I guess I'll do the call to `_listenToSocket` in another more appropriate place like in `ajax()`

**Comment by toovy** [comment]
I had the same thought, nevertheless the params of the ajax do not provide any hints about the used model. Looking forward for your fix :)

**Comment by huafu** [comment]
On it now, sorry for the delay!

**Comment by huafu** [comment]
@toovy I am short on time, can you test this one please? (put this in your `package.json` and run npm install before testing: `"ember-data-sails": "huafu/ember-data-sails#2914745"`)

Thanks in advance, lemme know if it works, I'll then merge it and create a release.
