### ISSUE TITLE
this.store.find with params

### ISSUE THREAD

**Issue by Kulja** [huafu/ember-data-sails#8]
Basically this is the issue that I am experiencing:

If in model hook in my route I have `return this.store.find('user');` everything is working fine (if new user is created I get notified and I see new user rendered on page).

On the other hand if I have `return this.store.find('estate', { limit:3 });` I get notified (`[ed-sails] triggering event user.created`) that user is created and also if I check out ember inspector I can see new user in data tab but new user is not rendered on page.

Is this intentional or is there something else going on here?

**Comment by huafu** [comment]
@Kulja `this.store.find('user', { limit:3 })` is returning a `RecordArray` of users where users are limited to `3` **by the API** and not by the **UI**, so creating a new user in the UI or API won't update this array.

With `this.store.find('user')` ED knows that you are asking all users, and returns a dynamic `RecordArray`, which will update automatically on new records.

To fix this, you can use `DS.Stroe.filter` as explained [here](http://emberjs.com/api/data/classes/DS.Store.html#method_filter) to create a dynamically updated filter:

```js
model: function () {
  this.store.find('user', { limit: 3 });
  return this.store.filter('user', function(record, i) { return i < 3; });
}
```

**Comment by Kulja** [comment]
Thank you for clearing things up with returning `RecordArray`.

I still have trouble achieving what I want. First thing is that `this.store.filter` has no index and I can't limit my model to only three users (`i` is undefined). 

Is there maybe a way I can handle in my route `[ed-sails] triggering event user.created` event? Something like `onMessgae` hook. I am guessing I could easily set there my model to only have three users.

**Comment by huafu** [comment]
Looks like you are missing some reading of the ember guides ;-)
Ok so if there is no `i` defined, you have to do the limit on your controller with a CP and in the route replace filter with all.

**Comment by Kulja** [comment]
I miss some reading on guides for sure :)

I know I can do it with findAll on route and then limit it in controller (I really don't want to fetch all users). I thought I can easily fetch only last three users and be notified only on new ones.

**Comment by huafu** [comment]
The all does not fetch anything but simply return an auto updated RecordArray of all fetched records so far. That is why you still need to do the find with the limit first, so that will fetch the last 3 records. Then the all will return the auto updated array, which in your controller you'll need to use to filter in another CP:

```js
last3Users: Ember.computed('model.@each.createdAt', function () {
  return this.get('model').sortBy('createdAt').reverse().slice(0, 3);
})
```
