### ISSUE TITLE
Authorization and query params

### ISSUE THREAD

**Issue by nrrso** [huafu/ember-data-sails#9]
I'm building an app that uses https://github.com/sane/sane-auth for api authentication. Basically it sets a token which is then send with each request from ember as part of an `authorization` header.

As far as I know, sockets don't allow setting the request header from the client side. 
So my first idea was, adding a query parameter to each socket request containing the token. This would be normally done setting `io.sails.connect(this.get('socketUrl'), {query: "param=my-param"});` or via io.sails.query.
However, this does not add any query parameters. 

This have given me some headache, as I'm not too familiar with sockets in general. Do you have any suggestions on how to add authorization to each request?

**Comment by huafu** [comment]
I am not an expert about sockets but afaik a socket opens a connection which stays alive and is used as a bi-directional tunnel between the server and the client, so once you connect, you get a session authenticated (which is done with the fake cookie automatically by sails). Then any exchange in this session with that socket can only be from the same client. So I'd store the connected user or whatever in te session on the backend and that would be the only needed thing.

But as I said I am not expert and I might have misunderstood one of the point of your issue.

**Comment by huafu** [comment]
To resume, a socket connect once, and then never connects again except if it looses the connection or if the user reload the page of course

**Comment by huafu** [comment]
Oh and what it looks like you want to do is sending a message thru the socket (the "header") which then could be handled by the server. You can use the sails socket service also provided by my adapter.

_I am actually in bed from my phone, will look deeper at it tomorrow_

**Comment by nrrso** [comment]
Wrapping my head around sockets seems like reading a book about sorcery :D However, I fixed the issue with a small, ugly hack to the `_request` Method of `sails-socket.js` and some additions to my sails policy: 

```
.../addon/adapters/sails-socket.js 

/**
   * Sends a request over the socket
   *
   * @since 0.0.11
   * @method _request
   * @param {Object} out
   * @param {String} url
   * @param {String} method
   * @param {Object} options
   * @returns {Ember.RSVP.Promise}
   * @private
   */
  _request: function(out, url, method, options) {
    out.protocol = 'socket';
    var rawToken = JSON.parse(localStorage.getItem('ember_simple_auth:session'));
    var myToken = (rawToken != null) ? '?token='+rawToken.access_token : null;
    return this.sailsSocket.request(method, url + myToken, options.data);
  }
  // Gets the Token and inserts it as part of the url
```

```
.../api/policies/checkToken.js

module.exports =
expressJwt({secret: secret,
            getToken: function fromHeaderOrQuerystring (req) {
                if (req.headers.authorization && req.headers.authorization.split(' ')[0] === 'Bearer') {
                    return req.headers.authorization.split(' ')[1];
                } else if (req.query && req.query.token) {
                  var key = req.query.token;
                  delete req.query.token;
                  return key;
                }
                return null;
            }
          });
```

With this, the api can check the token and allow access of each request to secured routes. Despite the fact that this now works, I'm still searching for a better way (preferably over a request header or the message body ).
Would gladly appreciate any ideas on this. ;-)

**Comment by huafu** [comment]
Well, still... the thing is that an http request is opening a connection for each request. So you **DO** need to send the auth thru a header, cookie, whatever...

A socket opens a connection per socket, and so per client. Once it's open, it uses this connection to send and receive messages, which are still exchanged with the same connection, so same client, so same auth.

Sails `fakes` request by sending thru the socket messages like this (or kinda): `{url: '/my/url', method: 'post', data: {...}}`. So it looks like a request, but still done in the same opened connection of that socket. So you do not need to send the auth for each **fake** request, just when you open the socket connection.

**Comment by nrrso** [comment]
My above "fix" is ignoring the fact that a socket connection is established only once, it's just temporary to keep building on parts of the frontend, while leaving the api secured. Could've written it more clearly though. 

Stil, I need to submit the token on when the socket wants to connect. As far as I could research I can pass meta-data like tokens either through Query Parameters or by emitting an Event. Because it seems quicker I decided to stick with Query Params.

https://github.com/auth0/blog/blob/master/_posts/2014-01-15-auth-with-socket-io.markdown#client-side
As stated in that post, I could pass a query Parameter, e.g. token="myToken", to `io.sails.connect()` similar to this:
```
function connect_socket (myToken) {
  var socket = io.connect('', {
    query: 'token=' + myToken
  });
```
However, setting a second argument to `io.sails.connect()` did not added a Query Param to the initial connection request. 
This leads me to my actual question: **How do I pass a message and additional information respectively to my socket when connecting?**

Can you provide any example to accomplish this ( maybe using the ` sails socket service` )? Thanks in advance for taking time.

P.S.: *Liked the Bold Type :D*

**Comment by huafu** [comment]
Just send a socket message with the token to authenticate with `sailsSocket.sendMessage(...)` or just `send` I forgot the API once the connection is done, that's all ;-)

**Comment by tibotiber** [comment]
Hi! Some ideas about this although it's been a while. I am now using [waterlock](http://waterlock.ninja) on sails side to handle authentication. It has a cool handling of stateless api requests by authenticating the session through the JWT token. However this requires to pass the token at each request for their `hasJsonWebToken` policy to validate. Then the issue @nrrso has met does make sense. I've had a similar approach of extending `_request`. My code is below:
```
import SailsSocketAdapter from 'ember-data-sails/adapters/sails-socket';

export default SailsSocketAdapter.extend({
    useCSRF: true,
    coalesceFindRequests: true,
    _request: function(out, url, method, options) {
        var jwt = this.container.lookup('simple-auth-session:main').content.access_token;
        url = (jwt) ? url+'?access_token='+jwt : url;
        return this._super(out, url, method, options);
    }
});
```

**Comment by huafu** [comment]
Well, as I said a socket is a connection which remains open, so until it closes you are sure to send data to the same process on the same server, so there is no need to send any token, this token must be saved on the server, contextually to that connection.

In Sails you _can_ use sockets to send messages thru this connection, messages which have attributes like `url` or `method`, to fake an http request per message.
